service: stripe-session
provider:
  name: aws
  runtime: nodejs12.x
  stage: test
  region: eu-central-1
package:
  include:
    - config/**
    - node_modules/**
  exclude:
    - package.json

functions:
  session:
    handler: session.createSession
    events:
      - http:
          path: create-session
          method: any
          cors: true
